-- Modified by:

create table Category(
	category_name char(10) not null primary key,
	checkout_period integer,
	max_books_out integer
);

create table Borrower(
	borrower_id char(10) not null primary key,
	last_name char(20),
	first_name char(20),
	category_name char(10) not null references Category(category_name)
);

create table Borrower_phone(
    borrower_id char(10) not null references Borrower(borrower_id),
    phone char(20)
);

create table Book_info(
	call_number char(20) not null primary key,
	title char(50),
	format char(2)
);

-- The code supplied below for bar_code will cause it to be generated
-- automatically when a new Book is added to the database

create table Book(
	call_number char(20) not null references Book_info(call_number),
	copy_number smallint not null,
	bar_code integer generated by default as identity,
	primary key (call_number, copy_number)
);

create table Book_author(
	call_number char(20) not null references Book_info(call_number),
	author_name char(20) not null
);

create table Book_keyword(
    call_number char(20) not null references Book_info(call_number),
    keyword varchar(20) not null
);

create table Checked_out(
	call_number char(20) not null,
	copy_number smallint not null,
	borrower_id char(10) not null,
	date_due date,
	foreign key (call_number, copy_number) references Book(call_number, copy_number)
);

create table Fine(
	borrower_id char(10) not null references Borrower(borrower_id),
	title char(50) not null,
	date_due date not null,
	date_returned date,
	amount numeric(10,2),
	primary key (borrower_id, title, date_due)
);
