-- Modified by:

create table Category(
	category_name char(10),
	checkout_period integer,
	max_books_out integer
);

create table Borrower(
	borrower_id char(10),
	last_name char(20),
	first_name char(20),
	category_name char(10)
);

create table Borrower_phone(
    borrower_id char(10),
    phone char(20)
);

create table Book_info(
	call_number char(20),
	title char(50),
	format char(2)
);

-- The code supplied below for accession_number will cause it to be generated
-- automatically when a new Book is added to the database

create table Book(
	call_number char(20),
	copy_number smallint,
	accession_number integer generated by default as identity
);

create table Book_author(
	call_number char(20),
	author_name char(20)
);

create table Book_keyword(
    call_number char(20),
    keyword varchar(20)
);

create table Checked_out(
	call_number char(20),
	copy_number smallint,
	borrower_id char(10),
	date_due date
);

create table Fine(
	borrower_id char(10),
	title char(50),
	date_due date,
	date_returned date,
	amount numeric(10,2)
);
